[project]
name = "transcription-translation-app"
version = "0.1.0"
description = "Audio transcription and text translation application"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.46.1",
    "numpy",
    "requests",
    "pydub",
    "tqdm",
    "nltk",
]